export const countries = [
    { code: 'AF', name: 'Afghanistan', flag: "https://flagsapi.com/AF/flat/64.png" },
    { code: 'AL', name: 'Albania', flag: "https://flagsapi.com/AL/flat/64.png" },
    { code: 'DZ', name: 'Algeria', flag: "https://flagsapi.com/DZ/flat/64.png" },
    { code: 'AS', name: 'American Samoa', flag: "https://flagsapi.com/AS/flat/64.png" },
    { code: 'AD', name: 'Andorra', flag: "https://flagsapi.com/AD/flat/64.png" },
    { code: 'AO', name: 'Angola', flag: "https://flagsapi.com/AO/flat/64.png" },
    { code: 'AI', name: 'Anguilla', flag: "https://flagsapi.com/AI/flat/64.png" },
    { code: 'AQ', name: 'Antarctica', flag: "https://flagsapi.com/AQ/flat/64.png" },
    { code: 'AG', name: 'Antigua and Barbuda', flag: "https://flagsapi.com/AG/flat/64.png" },
    { code: 'AR', name: 'Argentina', flag: "https://flagsapi.com/AR/flat/64.png" },
    { code: 'AM', name: 'Armenia', flag: "https://flagsapi.com/AM/flat/64.png" },
    { code: 'AW', name: 'Aruba', flag: "https://flagsapi.com/AW/flat/64.png" },
    { code: 'AU', name: 'Australia', flag: "https://flagsapi.com/AU/flat/64.png" },
    { code: 'AT', name: 'Austria', flag: "https://flagsapi.com/AT/flat/64.png" },
    { code: 'AZ', name: 'Azerbaijan', flag: "https://flagsapi.com/AZ/flat/64.png" },
    { code: 'BS', name: 'Bahamas', flag: "https://flagsapi.com/BS/flat/64.png" },
    { code: 'BH', name: 'Bahrain', flag: "https://flagsapi.com/BH/flat/64.png" },
    { code: 'BD', name: 'Bangladesh', flag: "https://flagsapi.com/BD/flat/64.png" },
    { code: 'BB', name: 'Barbados', flag: "https://flagsapi.com/BB/flat/64.png" },
    { code: 'BY', name: 'Belarus', flag: "https://flagsapi.com/BY/flat/64.png" },
    { code: 'BE', name: 'Belgium', flag: "https://flagsapi.com/BE/flat/64.png" },
    { code: 'BZ', name: 'Belize', flag: "https://flagsapi.com/BZ/flat/64.png" },
    { code: 'BJ', name: 'Benin', flag: "https://flagsapi.com/BJ/flat/64.png" },
    { code: 'BM', name: 'Bermuda', flag: "https://flagsapi.com/BM/flat/64.png" },
    { code: 'BT', name: 'Bhutan', flag: "https://flagsapi.com/BT/flat/64.png" },
    { code: 'BO', name: 'Bolivia', flag: "https://flagsapi.com/BO/flat/64.png" },
    { code: 'BA', name: 'Bosnia and Herzegovina', flag: "https://flagsapi.com/BA/flat/64.png" },
    { code: 'BW', name: 'Botswana', flag: "https://flagsapi.com/BW/flat/64.png" },
    { code: 'BR', name: 'Brazil', flag: "https://flagsapi.com/BR/flat/64.png" },
    { code: 'BN', name: 'Brunei', flag: "https://flagsapi.com/BN/flat/64.png" },
    { code: 'BG', name: 'Bulgaria', flag: "https://flagsapi.com/BG/flat/64.png" },
    { code: 'BF', name: 'Burkina Faso', flag: "https://flagsapi.com/BF/flat/64.png" },
    { code: 'BI', name: 'Burundi', flag: "https://flagsapi.com/BI/flat/64.png" },
    { code: 'KH', name: 'Cambodia', flag: "https://flagsapi.com/KH/flat/64.png" },
    { code: 'CM', name: 'Cameroon', flag: "https://flagsapi.com/CM/flat/64.png" },
    { code: 'CA', name: 'Canada', flag: "https://flagsapi.com/CA/flat/64.png" },
    { code: 'CV', name: 'Cape Verde', flag: "https://flagsapi.com/CV/flat/64.png" },
    { code: 'CF', name: 'Central African Republic', flag: "https://flagsapi.com/CF/flat/64.png" },
    { code: 'TD', name: 'Chad', flag: "https://flagsapi.com/TD/flat/64.png" },
    { code: 'CL', name: 'Chile', flag: "https://flagsapi.com/CL/flat/64.png" },
    { code: 'CN', name: 'China', flag: "https://flagsapi.com/CN/flat/64.png" },
    { code: 'CO', name: 'Colombia', flag: "https://flagsapi.com/CO/flat/64.png" },
    { code: 'KM', name: 'Comoros', flag: "https://flagsapi.com/KM/flat/64.png" },
    { code: 'CG', name: 'Congo - Brazzaville', flag: "https://flagsapi.com/CG/flat/64.png" },
    { code: 'CD', name: 'Congo - Kinshasa', flag: "https://flagsapi.com/CD/flat/64.png" },
    { code: 'CR', name: 'Costa Rica', flag: "https://flagsapi.com/CR/flat/64.png" },
    { code: 'HR', name: 'Croatia', flag: "https://flagsapi.com/HR/flat/64.png" },
    { code: 'CU', name: 'Cuba', flag: "https://flagsapi.com/CU/flat/64.png" },
    { code: 'CY', name: 'Cyprus', flag: "https://flagsapi.com/CY/flat/64.png" },
    { code: 'CZ', name: 'Czechia', flag: "https://flagsapi.com/CZ/flat/64.png" },
    { code: 'DK', name: 'Denmark', flag: "https://flagsapi.com/DK/flat/64.png" },
    { code: 'DJ', name: 'Djibouti', flag: "https://flagsapi.com/DJ/flat/64.png" },
    { code: 'DM', name: 'Dominica', flag: "https://flagsapi.com/DM/flat/64.png" },
    { code: 'DO', name: 'Dominican Republic', flag: "https://flagsapi.com/DO/flat/64.png" },
    { code: 'EC', name: 'Ecuador', flag: "https://flagsapi.com/EC/flat/64.png" },
    { code: 'EG', name: 'Egypt', flag: "https://flagsapi.com/EG/flat/64.png" },
    { code: 'SV', name: 'El Salvador', flag: "https://flagsapi.com/SV/flat/64.png" },
    { code: 'GQ', name: 'Equatorial Guinea', flag: "https://flagsapi.com/GQ/flat/64.png" },
    { code: 'ER', name: 'Eritrea', flag: "https://flagsapi.com/ER/flat/64.png" },
    { code: 'EE', name: 'Estonia', flag: "https://flagsapi.com/EE/flat/64.png" },
    { code: 'SZ', name: 'Eswatini', flag: "https://flagsapi.com/SZ/flat/64.png" },
    { code: 'ET', name: 'Ethiopia', flag: "https://flagsapi.com/ET/flat/64.png" },
    { code: 'FJ', name: 'Fiji', flag: "https://flagsapi.com/FJ/flat/64.png" },
    { code: 'FI', name: 'Finland', flag: "https://flagsapi.com/FI/flat/64.png" },
    { code: 'FR', name: 'France', flag: "https://flagsapi.com/FR/flat/64.png" },
    { code: 'GA', name: 'Gabon', flag: "https://flagsapi.com/GA/flat/64.png" },
    { code: 'GM', name: 'Gambia', flag: "https://flagsapi.com/GM/flat/64.png" },
    { code: 'GE', name: 'Georgia', flag: "https://flagsapi.com/GE/flat/64.png" },
    { code: 'DE', name: 'Germany', flag: "https://flagsapi.com/DE/flat/64.png" },
    { code: 'GH', name: 'Ghana', flag: "https://flagsapi.com/GH/flat/64.png" },
    { code: 'GR', name: 'Greece', flag: "https://flagsapi.com/GR/flat/64.png" },
    { code: 'GD', name: 'Grenada', flag: "https://flagsapi.com/GD/flat/64.png" },
    { code: 'GT', name: 'Guatemala', flag: "https://flagsapi.com/GT/flat/64.png" },
    { code: 'GN', name: 'Guinea', flag: "https://flagsapi.com/GN/flat/64.png" },
    { code: 'GW', name: 'Guinea-Bissau', flag: "https://flagsapi.com/GW/flat/64.png" },
    { code: 'GY', name: 'Guyana', flag: "https://flagsapi.com/GY/flat/64.png" },
    { code: 'HT', name: 'Haiti', flag: "https://flagsapi.com/HT/flat/64.png" },
    { code: 'HN', name: 'Honduras', flag: "https://flagsapi.com/HN/flat/64.png" },
    { code: 'HU', name: 'Hungary', flag: "https://flagsapi.com/HU/flat/64.png" },
    { code: 'IS', name: 'Iceland', flag: "https://flagsapi.com/IS/flat/64.png" },
    { code: 'IN', name: 'India', flag: "https://flagsapi.com/IN/flat/64.png" },
    { code: 'ID', name: 'Indonesia', flag: "https://flagsapi.com/ID/flat/64.png" },
    { code: 'IR', name: 'Iran', flag: "https://flagsapi.com/IR/flat/64.png" },
    { code: 'IQ', name: 'Iraq', flag: "https://flagsapi.com/IQ/flat/64.png" },
    { code: 'IE', name: 'Ireland', flag: "https://flagsapi.com/IE/flat/64.png" },
    { code: 'IL', name: 'Israel', flag: "https://flagsapi.com/IL/flat/64.png" },
    { code: 'IT', name: 'Italy', flag: "https://flagsapi.com/IT/flat/64.png" },
    { code: 'JM', name: 'Jamaica', flag: "https://flagsapi.com/JM/flat/64.png" },
    { code: 'JP', name: 'Japan', flag: "https://flagsapi.com/JP/flat/64.png" },
    { code: 'JO', name: 'Jordan', flag: "https://flagsapi.com/JO/flat/64.png" },
    { code: 'KZ', name: 'Kazakhstan', flag: "https://flagsapi.com/KZ/flat/64.png" },
    { code: 'KE', name: 'Kenya', flag: "https://flagsapi.com/KE/flat/64.png" },
    { code: 'KI', name: 'Kiribati', flag: "https://flagsapi.com/KI/flat/64.png" },
    { code: 'KR', name: 'Korea (South)', flag: "https://flagsapi.com/KR/flat/64.png" },
    { code: 'KW', name: 'Kuwait', flag: "https://flagsapi.com/KW/flat/64.png" },
    { code: 'KG', name: 'Kyrgyzstan', flag: "https://flagsapi.com/KG/flat/64.png" },
    { code: 'LA', name: 'Laos', flag: "https://flagsapi.com/LA/flat/64.png" },
    { code: 'LV', name: 'Latvia', flag: "https://flagsapi.com/LV/flat/64.png" },
    { code: 'LB', name: 'Lebanon', flag: "https://flagsapi.com/LB/flat/64.png" },
    { code: 'LS', name: 'Lesotho', flag: "https://flagsapi.com/LS/flat/64.png" },
    { code: 'LR', name: 'Liberia', flag: "https://flagsapi.com/LR/flat/64.png" },
    { code: 'LY', name: 'Libya', flag: "https://flagsapi.com/LY/flat/64.png" },
    { code: 'LI', name: 'Liechtenstein', flag: "https://flagsapi.com/LI/flat/64.png" },
    { code: 'LT', name: 'Lithuania', flag: "https://flagsapi.com/LT/flat/64.png" },
    { code: 'LU', name: 'Luxembourg', flag: "https://flagsapi.com/LU/flat/64.png" },
    { code: 'MG', name: 'Madagascar', flag: "https://flagsapi.com/MG/flat/64.png" },
    { code: 'MW', name: 'Malawi', flag: "https://flagsapi.com/MW/flat/64.png" },
    { code: 'MY', name: 'Malaysia', flag: "https://flagsapi.com/MY/flat/64.png" },
];